src/joyage/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'joyage.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('movies.urls', namespace='movies'))
]

src/movies/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^movie/(?P<movie_id>[0-9]+)$', views.movie, name='movie'),
]

src/movies/models.py
from django.db import models


class Tag(models.Model):
    name    = models.CharField(max_length=40)

    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.name

class Movie(models.Model):
    name    = models.CharField(max_length=256)
    tags    = models.ManyToManyField(Tag)
    image   = models.CharField(max_length=256)
    screen_format   = models.CharField(max_length=256, default="Information Not Available")
    duration    = models.PositiveIntegerField() # Movie run time in minutes

    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.name

    def get_duration(self):
        hrs = self.duration // 60
        mins    = self.duration % 60
        return str(hrs) + ' hr ' + str(mins) + ' min'

class Theater(models.Model):
    name    = models.CharField(max_length=256)
    city    = models.CharField(max_length=4)
    address = models.CharField(max_length=256)
    page    = models.CharField(max_length=256)  # Theatre link (page)
    movies  = models.ManyToManyField(Movie, through='Show')

    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.name


class Show(models.Model):
    theater = models.ForeignKey(Theater)
    movie   = models.ForeignKey(Movie)
    time    = models.TimeField()

    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)

    def __str__(self):
        return '"' + str(self.movie) + '" in ' + str(self.theater) + ', at ' + str(self.time)

    def get_timing(self):
        return self.time.strftime('%I:%M %p')

src/movies/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from .models import Movie, Show


def home(request):
    page_no = int(request.GET.get('page', '1'))
    all_movies  = Movie.objects.all()
    pages   = Paginator(all_movies, 12)
    return render(request, 'movies/index.html',
        {
            'page': pages.page(page_no),
            'number': pages.num_pages
        })

def movie(request, movie_id):
    movie   = Movie.objects.get(id=movie_id)
    shows   = Show.objects.filter(movie=movie)

    # Using python dictionaries to aggregate show times of theaters
    show_times   = {}
    for show in shows:
        if show.theater in show_times:
            show_times[show.theater] += [show.time.strftime('%I:%M %p'),]
        else:
            show_times[show.theater] = [show.time.strftime('%I:%M %p'),]

    # As dictionaries cannot be paginated, it is converted to list of lists
    show_list = []
    for theater, shows in show_times.items():
        show_list += [[theater.name, theater.address, shows]]

    page_no = int(request.GET.get('page', '1'))
    show_pages   = Paginator(show_list, 10)

    return render(request, 'movies/shows.html',
        {
            'movie': movie,
            'shows': show_pages.page(page_no),
            'number': show_pages.num_pages
        })

src/movies/templates/layouts/default.html
{% load staticfiles %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/theme/forms.css' %}" />
        <link rel="stylesheet" tyep="text/css" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/customizations.css' %}" type="text/css">
        {% block stylesheets %}
        {% endblock %}

    </head>
    <body>
        <nav class="navbar navbar-default header" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Joyage</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/">Home</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>

        <div class="container">
            <div class="row">
                <hr>
                <footer>
                    <p>&copy;PGS </p>
                </footer>
            </div>
        </div> <!-- /container -->

        {% block scriptsPrepend %}
        {% endblock %}
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js" ></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>

        <!-- Plugin JavaScript -->
        <script src="/js/jquery.easing.min.js"></script>
        <script src="/js/jquery.fittext.js"></script>
        <script src="/js/wow.min.js"></script>
        {% block scriptsAppend %}
        {% endblock %}
    </body>
</html>

src/movies/templates/movies/index.html
{% extends "layouts/default.html" %}

{% block content %}
    <h3>All Movies</h3>
    <div>(Page {{ page.number }} of {{ number }})</div>

    <div class="col-xs-12">
        <nav>
            <ul class="pager">
                {%  if not page.has_previous %}
                <li class="previous disabled">
                    <a href="#">
                        <span aria-hidden="true">&larr;</span>
                        Previous
                    </a>
                </li>
                {% else %}
                <li class="previous">
                    <a href="?page={{page.previous_page_number}}">
                        <span aria-hidden="true">&larr;</span>
                        Previous
                    </a>
                </li>
                {% endif %}
                {%  if not page.has_next %}
                <li class="next disabled">
                    <a href="#">
                        Next
                        <span aria-hidden="true">&rarr;</span>
                    </a>
                </li>
                {% else %}
                <li class="next">
                    <a href="?page={{page.next_page_number}}">
                        Next
                        <span aria-hidden="true">&rarr;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>

    {% for movie in page %}

        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-6">
            <div onclick="location.href='{% url 'movies:movie' movie.id %}'" class="movie-banner">
                <img src="{{ movie.image }}" alt="{{ movie.name }}"></img>
                <div class="board">
                    <h4 class="movie-title">
                        <a href="{% url 'movies:movie' movie.id %}">{{ movie.name }}</a>
                    </h4>
                </div>
            </div>
        </div>

    {% endfor %}

    <div class="col-xs-12">
        <nav>
            <ul class="pager">
                {%  if not page.has_previous %}
                <li class="previous disabled">
                    <a href="#">
                        <span aria-hidden="true">&larr;</span>
                        Previous
                    </a>
                </li>
                {% else %}
                <li class="previous">
                    <a href="?page={{page.previous_page_number}}">
                        <span aria-hidden="true">&larr;</span>
                        Previous
                    </a>
                </li>
                {% endif %}
                {%  if not page.has_next %}
                <li class="next disabled">
                    <a href="#">
                        Next
                        <span aria-hidden="true">&rarr;</span>
                    </a>
                </li>
                {% else %}
                <li class="next">
                    <a href="?page={{page.next_page_number}}">
                        Next
                        <span aria-hidden="true">&rarr;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

src/movies/templates/movies/shows.html
{% extends "layouts/default.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12">
                <div class="movie-poster">
                    <img src="{{ movie.image }}" alt="{{ movie.name }}"></img>
                </div>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12">
                <div class="board">
                    <h3 class="movie-shows-title">
                        {{ movie.name }}
                        <div class="movie-duration">
                            ({{ movie.get_duration }})
                        </div>
                    </h3>
                    <div>
                        Screen format:
                        {{ movie.screen_format }}
                    </div>

                    <div>
                        Genres:
                        {% for tag in movie.tags.all %}
                            <span class="label label-primary">{{ tag.name }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <nav>
                            <ul class="pager">
                                {%  if not shows.has_previous %}
                                <li class="previous disabled">
                                    <a href="#">
                                        <span aria-hidden="true">&larr;</span>
                                        Previous
                                    </a>
                                </li>
                                {% else %}
                                <li class="previous">
                                    <a href="?page={{shows.previous_page_number}}">
                                        <span aria-hidden="true">&larr;</span>
                                        Previous
                                    </a>
                                </li>
                                {% endif %}
                                <li>(Page {{ shows.number }} of {{ number }})</li>
                                {%  if not shows.has_next %}
                                <li class="next disabled">
                                    <a href="#">
                                        Next
                                        <span aria-hidden="true">&rarr;</span>
                                    </a>
                                </li>
                                {% else %}
                                <li class="next">
                                    <a href="?page={{shows.next_page_number}}">
                                        Next
                                        <span aria-hidden="true">&rarr;</span>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>

                <div class="movie-shows">
                    {% for show in shows %}
                        <div class="theater-show">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title">
                                        <b>Theater: </b>{{ show.0 }}
                                        <span class="badge" title="{{show.2|length}} show(s)">{{ show.2|length }}</span>
                                    </h3>
                                </div>
                                <div class="panel-body">
                                    {% for time in show.2 %}
                                        <button class="btn btn-success" type="button" href="#">
                                            {{time}}
                                        </button>
                                    {% endfor %}
                                </div>
                                <div class="panel-footer">
                                    <div class="show-theater-address">
                                        <b>Address: </b>{{ show.1 }}
                                    </div>
                                </div>
                            </div>

                        </div>
                    {% endfor %}
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <nav>
                            <ul class="pager">
                                {%  if not shows.has_previous %}
                                <li class="previous disabled">
                                    <a href="#">
                                        <span aria-hidden="true">&larr;</span>
                                        Previous
                                    </a>
                                </li>
                                {% else %}
                                <li class="previous">
                                    <a href="?page={{shows.previous_page_number}}">
                                        <span aria-hidden="true">&larr;</span>
                                        Previous
                                    </a>
                                </li>
                                {% endif %}
                                <li>(Page {{ shows.number }} of {{ number }})</li>
                                {%  if not shows.has_next %}
                                <li class="next disabled">
                                    <a href="#">
                                        Next
                                        <span aria-hidden="true">&rarr;</span>
                                    </a>
                                </li>
                                {% else %}
                                <li class="next">
                                    <a href="?page={{shows.next_page_number}}">
                                        Next
                                        <span aria-hidden="true">&rarr;</span>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}